
version: "3.8"

networks:
    innoscriptaapp-network:
        driver: bridge

services:
    innoscriptaapp:
        build: 
            context: ./
            dockerfile: Dockerfile
        image: digitalocean.com/php # laravel8-php-fpm-80
        container_name: innoscriptaapp
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes: 
            - ./src:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks: 
            - innoscriptaapp-network
    
    innoscriptamysql:
        image: mysql:latest
        container_name: innoscriptadatabase
        command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx --lower_case_table_names=1 --sql_mode=""
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            PMA_HOST: innoscriptadatabase
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: innoscripta_news
            MYSQL_USER: innoscripta_news
            MYSQL_PASSWORD: inn05cr1pta
            SERVICE_TAGS: dev
            SERVICE_NAME: innoscriptadatabase
        security_opt:
            - seccomp:unconfined
        volumes:
            - ./mysql/sql:/docker-entrypoint-initdb.d
            - ./mysql/data:/var/lib/mysql           
            - ./mysql/conf:/etc/mysql/conf.d
        networks:
            - innoscriptaapp-network

    innoscripta-redis:
        image: redis:6.2-alpine
        container_name: innoscripta-redis
        restart: always
        ports:
            - '6479:6479'
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes:
            - ./cache:/data
        networks:
            - innoscriptaapp-network

    innoscriptanginx:
        image: nginx:1.19.8-alpine
        container_name: innoscriptanginx
        restart: unless-stopped
        tty: true
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - ./src:/var/www
            - ./nginx/conf:/etc/nginx/conf.d
        networks: 
            - innoscriptaapp-network
